block: blk-mq: fix conflicting types
Apparently the source has void instead of bool.

../block/blk-mq.c:1607:6: error: conflicting types for 'blk_mq_run_hw_queue'
 1607 | void blk_mq_run_hw_queue(struct blk_mq_hw_ctx *hctx, bool async)
      |      ^
../include/linux/blk-mq.h:327:6: note: previous declaration is here
  327 | bool blk_mq_run_hw_queue(struct blk_mq_hw_ctx *hctx, bool async);
      |      ^
../block/blk-mq.c:1627:3: error: void function 'blk_mq_run_hw_queue' should not return a value [-Wreturn-mismatch]
 1627 |                 return true;
      |                 ^      ~~~~
../block/blk-mq.c:1630:2: error: void function 'blk_mq_run_hw_queue' should not return a value [-Wreturn-mismatch]
 1630 |         return false;
      |         ^      ~~~~~
3 errors generated.

Signed-off-by: xfwdrev <74693315+xfwdrev@users.noreply.github.com>